

- name: Create MariaDB user
  community.mysql.mysql_user:
    name: "mediawiki"
    host: "%"
    password: "{{ mediawiki.mariadb.password }}"
    check_implicit_admin: yes
    login_user: "root"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "{{ mediawiki.mariadb.dbname }}.*:ALL"


- name: Create MariaDB database
  community.mysql.mysql_db:
    name: "{{ mediawiki.mariadb.dbname }}"
    check_implicit_admin: yes
    login_user: "root"
    login_unix_socket: /var/run/mysqld/mysqld.sock


#- name: Create MariaDB role
#  community.mysql.mysql_role:
#    name: "mediawiki"
#    members: "'mediawiki'@%"
#    priv: "{{ mediawiki.mariadb.dbname }}.*:ALL"
#    check_implicit_admin: yes
#    login_user: "root"
#    login_unix_socket: /var/run/mysqld/mysqld.sock
#  delegate_to: server01.forberger-online.de




